apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: whknmqx8w-nodejs 
  janus-idp.io/tekton: whknmqx8w-nodejs
  backstage.io/kubernetes-id: whknmqx8w-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: whknmqx8w-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml